version: "3.9.1"
services:
    app:
        build: .
        ports:
          - 8080:8080
        image: datacontrol:latest
        container_name: datacontrol_container
        command: python manage.py runserver 0.0.0.0:8080
        depends_on:
          - db
    db:
      image: postgres
      volumes:
        - ./db_data:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=admin
        - POSTGRES_DB=djproject
      container_name: postgres_db

