# Generated by Django 4.2.7 on 2023-11-21 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название клуба')),
            ],
            options={
                'verbose_name': 'Клуб',
                'verbose_name_plural': 'Клубы',
            },
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=100, verbose_name='ФИО')),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.club')),
            ],
            options={
                'verbose_name': 'Эксперт',
                'verbose_name_plural': 'Эксперты',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='ФИО')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('mother', models.CharField(max_length=200, verbose_name='Мать')),
                ('father', models.CharField(max_length=200, verbose_name='Отец')),
                ('medal', models.CharField(db_index=True, max_length=100, verbose_name='Медаль')),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.club')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
        migrations.CreateModel(
            name='Ring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=100, verbose_name='Порода')),
            ],
            options={
                'verbose_name': 'Ринг',
                'verbose_name_plural': 'Ринги',
            },
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='participant',
            name='ring_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.ring'),
        ),
        migrations.AddField(
            model_name='expert',
            name='ring_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.ring'),
        ),
    ]
