# Generated by Django 4.2.7 on 2023-11-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_club_expert_participant_ring_delete_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Кличка'),
        ),
    ]
